name: flyball_ring_lights
description: Flyball Ring Lights by Menai Muttineers - Rev 0.1 prototype
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  audioplayers: ^6.5.1
  wakelock_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/red_beep.wav
    - assets/audio/go_beep.wav
