import 'package:flutter/material.dart';
import '../models/local_profile.dart';
import '../services/local_profile_service.dart';
import '../theme/app_theme.dart';
import 'ring/ring_screen.dart';
import 'welcome_screen.dart';

class HomeScreen extends StatelessWidget{final LocalProfile profile;const HomeScreen({super.key,required this.profile});Future<void> _reset(BuildContext c) async {await LocalProfileService().clear();if(!c.mounted)return;Navigator.of(c).pushAndRemoveUntil(MaterialPageRoute(builder:(_)=>const WelcomeScreen()),(_)=>false);} @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(profile.clubName),actions:[PopupMenuButton<String>(onSelected:(v){if(v=='reset')_reset(context);},itemBuilder:(_)=>const [PopupMenuItem(value:'reset',child:Text('Reset Rev 0.1 profile'))])]),body:SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[Text('Ahoy ${profile.displayName}',style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:6),const Text('Ready to train?',style:TextStyle(color:AppTheme.textMuted,fontSize:17)),const SizedBox(height:28),SizedBox(height:120,child:FilledButton(onPressed:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>const RingScreen())),style:FilledButton.styleFrom(backgroundColor:AppTheme.gold,foregroundColor:Colors.black),child:const Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.play_arrow_rounded,size:42),SizedBox(height:4),Text('START A RING',style:TextStyle(fontSize:23))]))),const SizedBox(height:18),const _Tile(icon:Icons.link,title:'Join existing ring',subtitle:'Room tokens + QR joining arrive in Rev 0.2'),const _Tile(icon:Icons.pets_outlined,title:'Dogs & Pass Planner',subtitle:'Start marks and release plans arrive in Rev 0.3'),const _Tile(icon:Icons.analytics_outlined,title:'Training history',subtitle:'Fault analysis and reports arrive after live-ring testing'),const SizedBox(height:24),const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('REV 0.1 PURPOSE\n\nProve the local lights, timer, controls and sound are excellent before any cloud synchronisation is added.',style:TextStyle(color:AppTheme.textMuted,height:1.4))))])));
}
class _Tile extends StatelessWidget{final IconData icon;final String title,subtitle;const _Tile({required this.icon,required this.title,required this.subtitle});@override Widget build(BuildContext context)=>Card(child:ListTile(leading:Icon(icon,color:AppTheme.gold),title:Text(title),subtitle:Text(subtitle),trailing:const Icon(Icons.lock_outline,color:Colors.white24)));}
